### PR TITLE
Update fr.sh

### PR DESCRIPTION
**Pull request by j1nxd071r**
Almost complete french translation. Indented what I couldnt translate by myself.

### CODE REVIEW

**Comment by deltaxflux** [comment]
Merci :)

**Comment by j1nxd071r** [comment]
@deltaxflux Not a python dev atm so if you give me some hints on the lines I indented I probably could translate them too!

**Comment by deltaxflux** [comment]
Only lines inside the quotes need to translate. They are used as variables and it is required that they have the same name. Fluxion is mostly written in bash. Python has mostly nothing to do with that.

**Comment by j1nxd071r** [comment]
All right. Do we need a translation on those bold things?

FLUXIONKillingProcessNotice="Killing ${CGry}\$**targetID**$CClr"
FLUXIONDisablingCleaningIPTablesNotice="Nettoyage de ${CGry}**iptables**"
FLUXIONRestoringTputNotice="Restauration de ${CGry}**tput**"
FLUXIONDeletingFilesNotice="Suppression ${CGry}**files**"
FLUXIONRestartingNetworkManagerNotice="Redémarrage de ${CGry}**Network-Manager**"

**Comment by deltaxflux** [comment]
Yes but only if it is wrong or if there are English words inside:
`FLUXIONKillingProcessNotice="Killing ${CGry}$targetID$CClr" 
FLUXIONKillingProcessNotice="Meurtre ${CGry}$targetID$CClr"`

Note all words started with $ or ${} or variables don't translate them. Translate only text inside the quotes. **Like**
FLUXIONKillingProcessNotice="Killing ${CGry}$targetID$CClr"
VariableName="TEXT"

**Pull request merged**
