### PR TITLE
Patch 3

### PR DESCRIPTION
**Pull request by djmeero**
**What kind of change does this PR introduce?**
New feature

**Does this PR introduce a breaking change?**
I hope not :grinning:

### CODE REVIEW

**Comment by djmeero** [comment]
It needs /misc/sounds/wav files ... but I can't upload them

**Comment by deltaxflux** [comment]
Well, I like the idea but in general I don't think that this has no purpose for fluxion. It could be disturbing if you have a welcome sound. 

I guess we talked about ealier and I thought that you have changed the UI or something and not sounds. 

I see that you have changed something at the hostapd file. What is the purpose?

**Comment by djmeero** [comment]
well I used hostapd_cli to connect to hostapd server to get the infos when the client connect or disconnects so I can play the sound

**Comment by djmeero** [comment]
well I will keep them for me then :smile: if you need the wav files just let me know...I took them from "Hacker Evolution" =)

**Comment by deltaxflux** [comment]
I fine with that. Sorry I don't merge thanks anyway.

**Comment by zzt2584** [comment]
。。。

**Pull request closed without merging**
