### PR TITLE
Create Slovak.lang

### PR DESCRIPTION
**Pull request by c0mrade69**
generic slovak captive portal

**What kind of change does this PR introduce?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by deltaxflux** [comment]
So here is how you can push multiple files at once.
Open up your terminal and 
`git clone [your forked git site]`

_Do some changes._
Change into the cloned directory:
`cd fluxion`

Now we add all changed files:
`git add .`

_Note: You don't have to change the directory. You could also do:_
`git add fluxion/.`

Next you want to do is commit your changes 
`git commit -m "Your changes message"`

_-m for message_

Lastly you want to push that:
`git push`

Type your username and your password if you get prompt. This all sounds complicated but it isn't if you get into the git workflow you want to never miss.

**Comment by c0mrade69** [comment]
thank you very much sir!

**Comment by c0mrade69** [comment]
@deltaxflux you said: git clone [your forked git site]

by the forked site you mean c0mrade69/fluxion ?
if so..I see my repo is 32 commits behind.. what should I do ?

i also see :  You’re all set—the c0mrade69:patch-8 branch can be safely deleted. 
should I delete something somewhere? 

I'm really noob please have patience.. :)

**Comment by deltaxflux** [comment]
Sure first of all make sure that your branch is up to date:
 `git remote add upstream https://www.github.com/FluxionNetwork/fluxion `

After we update the repo:
`git fetch upstream`

**Comment by deltaxflux** [comment]
Edit: You can simple delete all patch branches but there all gone with the update I think.

**Comment by c0mrade69** [comment]
thank you very much sir for your answer. 

but still I must miss something.. 

I did what you said:
image

but still my site or how to call it is not updated.. (on your repo I tapped fork and it moved me to my c0mrade69/fluxion repo..)

image

or the web and the local is something different? 
lost in Fork / branch etc,,,

**Comment by deltaxflux** [comment]
```git commit -m "Update files"
git push```

**Comment by c0mrade69** [comment]
thank you! will really try to get into commands ..

**Pull request merged**
