### PR TITLE
Installer update

### PR DESCRIPTION
**Pull request by MPX4132**
**What kind of change does this PR introduce?**
Updates and enhancements to installer.

**Summary**

The updater system was a bit outdated and hadn't been brought in line with the latest version of fluxion. This update makes the installer much more flexible, systematic, and consistent with method used throughout the project.

The installer is now built into fluxion and is launched every time the script is executed. It is now capable of installing updates, or any missing dependencies, for any system with a package manager.

Package managers may now be defined within fluxion/lib/installer/managers, and are automatically loaded depending on which system is being used to execute the script.

* [Report 1](https://github.com/FluxionNetwork/fluxion/issues/24)
* [Report 2](https://github.com/FluxionNetwork/fluxion/issues/82)
* [Report 3](https://github.com/FluxionNetwork/fluxion/issues/108)

**Does this PR introduce a breaking change?**

I don't think so.

**Other information**
The installer is much more systematic & [I believe] extensible.

### CODE REVIEW

**Comment by MPX4132** [comment]
Any objections?

**Comment by MPX4132** [comment]
If anyone's got any issues, let me know.

**Comment by deltaxflux** [comment]
Where is the new installer located ?

**Comment by MPX4132** [comment]
It's built in, but all logic/algorithms are in `lib/installer/InstallerUtils.sh` It'll automatically kick in if fluxion detects missing dependencies. It'll also kick in when there's a new update.

**Pull request merged**
