### PR TITLE
Minor change regarding recent events.

### PR DESCRIPTION
**Pull request by rad4day**
**What kind of change does this PR introduce?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by MPX4132** [comment]
What exactly are you referring to?

**Comment by MPX4132** [comment]
@deltaxflux Why did you merge the change? He committed a comment, and it's nonsense.

**Comment by MPX4132** [comment]
@deltaxflux I just looked at his commit history, this guys a fucking idiot. I'm reverting it.

**Comment by deltaxflux** [comment]
Don't worry,
He his a friend of mine and yes I know that this comment was senseless. However I visite with him the event and it was more or less a joke so if you have any problem with that I will remove it.

**Comment by MPX4132** [comment]
Oh okay, it’s fine then. That explains everything, my bad.

**Comment by deltaxflux** [comment]
Yeah don't worry. It's fine.

**Pull request merged**
