### PR TITLE
Remove unused files

### PR DESCRIPTION
**Pull request by Geczy**
**What kind of change does this PR introduce?**
* Relocating installer
* Installer was enhanced and it deprecated arch-install
* Removes 1.1mb logo that every person visiting this repo was loading...Changed to 15kb and offloading to imgur

**Summary**
Remove lots of unused installer files

**Does this PR introduce a breaking change?**
Moves the install.sh location to root directory

**Other information**
Readme updates to reflect breaking change

### CODE REVIEW

**Comment by MPX4132** [comment]
You'll have to wait for @deltaxflux  to merge this one, since you deleted some things related to the arch install. I think he mentioned there's some quirks with it, which is why the installer was there. I don't really know much about it, so I can't make an informed decision at this time.

**Comment by Geczy** [comment]
There's dependencies missing in the arch installer that the normal installer has. I think another solution has to be made that includes install.sh, then runs the arch separate installer stuff like remove.py and add.py

**Comment by Geczy** [comment]
Added back arch, we can at least do the logo update

**Comment by MPX4132** [comment]
Sorry, I don't think I can decide on the logo either since it's a project asset, and it may even be the "original."

**Comment by MPX4132** [comment]
Definitely agree with your changes, though.

**Comment by deltaxflux** [comment]
Agree with the changes. Thanks for pulling :)

**Comment by Geczy** [comment]
@deltaxflux so did you need arch install still? Because that wasn't in this pull

**Comment by deltaxflux** [comment]
Yes, or we make a global install which detects the used system.

**Comment by deltaxflux** [comment]
@Geczy can you make the pull request with deleting the files?

**Comment by MPX4132** [comment]
I think you mean "**without** deleting the files?"

**Comment by deltaxflux** [comment]
Yeah **without**

**Comment by Geczy** [comment]
What changes would I be making then?

**Comment by deltaxflux** [comment]
Only that you don't delete the logo folder. Every other change was good and should get included in this project.

**Pull request merged**
