### PR TITLE
Resumable attacks

### PR DESCRIPTION
**Pull request by MPX4132**
**What kind of change does this PR introduce?**

Feature: Implemented dynamic target tracking for all attacks.

**Summary**

Attacks may now select a interface for dynamic target tracking. Once a change is detected with the target, the attacks are relaunched with new parameters.

**Does this PR introduce a breaking change?**

I haven't thoroughly tested the script, however, everything seems to be working fine.

**Other information**
Finally got time to finish implementation, sorry.

### CODE REVIEW

**Comment by deltaxflux** [comment]
Well, give me some time. I will test this.

**Comment by deltaxflux** [comment]
As always thanks for your pr.

**Comment by MPX4132** [comment]
I tried both attacks with two different wireless interfaces. I was having the tracking interface alone, and the jammer and AP interfaces together. It worked fine, but I think people are going to have trouble with compatibility issues. I ran the attacks a couple of times, changing channels on my test network, and they seemed to work, but yeah, more testing is always good.

**Comment by MPX4132** [comment]
Just to clarify, I can't get target tracking to work with a single radio (using three virtual interfaces). I can only get it to work if I use a dedicated tracking interface, and the main interface with the AP service and the jamming.

**Comment by deltaxflux** [comment]
Yes I know, I guess this is also the main reason because wifiphisher also use also two wireless cards. I give it a quick run and it seems to be working.

**Comment by djmeero** [comment]
Just tested it. Does it stop when target turns off the AP?

**Comment by djmeero** [comment]
For me is stopping and it goes back to "Select SSL certificate" screen.. maybe because I'm using the internal WiFi for targeting and it barely see the target?

**Comment by MPX4132** [comment]
@djmeero It does not stop when the target AP is powered off. The SSL thing might be a bug, since I didn't test that part. I suggest disabling SSL altogether. It serves no purpose considering the fact the user's going to get warnings regardless, but it definitely might be a bug.

**Comment by MPX4132** [comment]
@djmeero I was suggesting disabling SSL while we get the bug fixed. I’ll try to look into it and fix it by tomorrow, since I’ve already shutdown the vm and I put my stuff away.

**Comment by deltaxflux** [comment]
Well you could also try to use another wireless card

**Comment by djmeero** [comment]
Yes..but I don't have one for the moment. I will try on a network that's in a good range of my internal card

**Comment by djmeero** [comment]
Because the signal is very poor on the internal card 
and doesn't see the target all the time so it can't update the parameters and maybe that's why it's stopping

**Comment by deltaxflux** [comment]
I guess @MPX4132 fixed a bug, does it work now?

**Comment by djmeero** [comment]
Oh, I saw just now..but I'm not home...soon as I get home I'll test it.

**Comment by djmeero** [comment]
Yup, it's working now, just tested

**Pull request merged**
