### PR TITLE
Update sk.sh

### PR DESCRIPTION
**Pull request by c0mrade69**
updated few fields

**What kind of change does this PR introduce?**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by MPX4132** [comment]
Thank you for your help, if you’re interested, you could also translate the language files for the attacks under the following directories:
```
fluxion/attacks/Captive Portal/language
fluxion/attacks/Handshake Snooper/language
```

**Comment by c0mrade69** [comment]
done buddy, sent pull, could you explain me how to edit more than 1 file in
1 pull ? :[ I'm really newbie and couldn't find it..

**Comment by MPX4132** [comment]
@c0mrade69 This is going to be a long explanation which I probably won't do again, so consider yourself lucky. Just know that it's **not hard or complicated, it's just a somewhat long process to setup, but then it's easy afterwards because it's already all setup**.

You can find a [guide by GitHub here](https://help.github.com/articles/fork-a-repo/), but I explained it below.

I'm not sure how you've been doing it up till now, but what you need to do is fork the repository first by clicking the fork button at the repository's home page. Forking will get you a copy of the repo you can work and edit as much as you like.

You'll then have to download that copy to your computer using the clone command from YOUR repo:
```
git clone --recursive https://github.com/MY_NAME_HERE/fluxion.git # Change this to your repo's address.
```
Now you have to add the original repository to get updates from it when things are changed:
```
git remote add upstream https://github.com/FluxionNetwork/fluxion.git
```
**This is where you'll have to start every time you want to commit a change. Follow all the steps below to make a merge request from your downloaded repository.**
You can now modify any and all files with whatever editor you like, so make all the changes you need. Once you've done that, and you're ready to commit, go to fluxion's root directory (the top most directory). You'll now have to update your local copy to make sure you have the latest version of the repo so your changes don't collide with anyone else's:
```
git fetch upstream
```
**If there are any changes, you must merge them with the following, otherwise skip this part below:** 
```
git merge upstream/master
```
Now you're ready to commit your changes, so check what you've modified:
```
cd fluxion # Change Directory to go to fluxion's root
git status
```
You'll see what's been modified in red. At this point you'll have to add the files you want to schedule for commit with the `git add` command:
```
git add path/to/file1.bs
git add path/to/file2.bs
```
However, you can also add all changes automatically with:
```
git add *
```

You can now check what you've added with `git status`. Everything shown in green is scheduled to be committed. Everything in red will not be committed. Now you can commit your changes with:

```
git commit -m "A short message here under 50-80 characters."
```
or a more elaborate commit message with:
```
git commit # BUT THIS ONE WILL OPEN VIM, A TEXT EDITOR WHICH YOU PROBABLY WONT LIKE.
```
Now you have to push changes to GitHub, by doing a push:
```
git push
```
Finally, you go back to GitHub and make a merge request from your repo to fluxion's repo. We'll then check out what you've committed and either accept or reject the merge.

**Comment by c0mrade69** [comment]
WOOow thank you soo much that you found time for poor c0mrade!! :) I really
appreciate it!

I read also the guide and it helped. I successfully updated local and web
repo :)

thank you sir.

**Comment by MPX4132** [comment]
Lol @c0mrade69 I just don't like having to explain all that, I've done it may times before so I really hate doing it. I'm glad you found it useful.

**Comment by c0mrade69** [comment]
Thank you again., I know how annoying is to explain something 1000x again
and again ! that's why I'm very happy you did it again 1001-st time to me!
:D

**Comment by deltaxflux** [comment]
It is the same like I wrote lol

**Comment by MPX4132** [comment]
@deltaxflux Yeah, sorry for that, I didn’t notice you had already explained till after I checked the other notifications, my bad.

**Comment by deltaxflux** [comment]
No problem I only was confused

**Pull request merged**
