### PR TITLE
Captive Portal - Fix deauth not launching on restore attack option

### PR DESCRIPTION
**Pull request by xpz3**

### CODE REVIEW

**Comment by strasharo** [comment]
Thanks a lot.

**Comment by MPX4132** [comment]
I don't believe this change is necessary @strasharo .

**Comment by xpz3** [comment]
https://github.com/FluxionNetwork/fluxion/commit/8cc52d4d63403df0ddcd8ecda85fa05089e0d59c
I've done the fix taking into account the above commit by usama. In this he adds a variable option_deauth and reads the type of jammer to be used. Based on this we can choose from mdk4, mdk3 or aireplay-ng. When a save_attack() is called it doesn't save the type of jammer used for current attack and so if the user wishes to restore an attack after fluxion completely exits, option_deauth variable has empty value and it will fail on to start the previously used jammer type.
Even if you have a global variable for jammer type, how can we use a previously used value without saving it first? Im confused.. @MPX4132

**Comment by MPX4132** [comment]
@xpz3 I’ll have to take a look at the source once I’m home. I don’t understand why he created another global for that, when there’s already a global signifying which deauthentication method to use.

**Comment by xpz3** [comment]
@MPX4132 before he did that commit, only mdk4 was the only available option in captive portal attack. You had a custom script for 5GHz though. So he added mdk3 and aireplay along with mdk4 which were later merged along with some other fixes from him. I think he forgot to add support for restore_attack with the newly added deauth methods. I saw someone asking for help regarding this in the discord channel. When i searched through issues i found out that a similar issue was closed without solution. That's why i added a quick fix for those who asked which was merged later.

**Pull request merged**
