### PR TITLE
Check existence of language files

### PR DESCRIPTION
**Pull request by Hritik14**
**What kind of change does this PR introduce?**

Feature

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

**Comment by MPX4132** [comment]
I don't understand why this is required, please elaborate. I'll merge it if you can give me a sensible reason to do so. It seems pointless to have find search for files, then verify they're still there.

**Comment by Hritik14** [comment]
@MPX4132 'Cause in a recent commit a language file sk.sh was uploaded with at `language/sk.sh` but not at other language locations. As this is an open source project, it is better to prevent any mishap in future.

**Comment by MPX4132** [comment]
Yeah, I’m sorry. I wasn’t aware of the problem till I read the thread where you mentioned to another guy he had to change the three locations. I’ll see if I can reopen this to accept it. Sorry for closing it, I wasn’t understanding it’s purpose.

**Comment by Hritik14** [comment]
I've created a new pull request. #276

**Pull request closed without merging**
