### PR TITLE
FLUXION V3

### PR DESCRIPTION
**Pull request by MPX4132**
**What kind of change does this PR introduce?**

This is a complete rewrite of the project, including subscripts, and support files.
The purpose of this rewrite is to make the script more extensible by abstracting behavior.
Most code in the project has been re-factored or rewritten with consistency in mind.

**Summary**

Generic behavior was re-factored and created into independent utils scripts in the lib directory.
Installation of new attacks or portals is done by adding a directory with contents, what is referred to here as "bundle."
Installation of custom portals/sites is now automatically detected by the scripts, once properly named and properly located.
Custom attacks are now possible via addition of "attack directory-bundles."
Custom attacks are automatically detected, once properly named and properly located.

Two attacks are available by default, "Captive Portal" attack, which is the old FakeAP attack, and "Snooper Attack," which is the handshake capturing script; both stand independently.

Everything is much more systematic/consistent now, which was the goal of the rewrite.

A lot more to list everything, check the commit history for more details.

**Does this PR introduce a breaking change?**

The translation files are definitely broken, since they're outdated, and they need updating.
I removed a fair bit of dead code and non-functional code.

**Other information**
The language files need to be brought in line with with the naming scheme of everything else.
I believe the script is much more extensible now.

### CODE REVIEW

**Comment by Blaxou** [comment]
Damn that's some massive dedication ! I love people like that ! Hope it will will be accepted !

**Comment by deltaxflux** [comment]
Thank you for this great pull request.

**Comment by Blaxou** [comment]
How are language files handled now ? Didn't have the time to examine the code :P

**Comment by strasharo** [comment]
kdk5l

**Pull request merged**
